# Generated by Django 6.0.6 on 2026-08-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_isbn_book_isbn_13_book_cover_type_and_more'),
        ('inventory', '0002_rack_shelf_floor_rack_unique_rack_code_per_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('DISCARDED', 'Discarded')], default='AVAILABLE', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='NEW', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_copies', to='inventory.shelf')),
            ],
            options={
                'ordering': ['accession_number'],
            },
        ),
    ]
