# Generated by Django 6.0.6 on 2026-06-28 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_usersubscription_last_billing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-billing_month'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'billing_month'), name='unique_subscription_month')],
            },
        ),
    ]
