# Generated by Django 6.0.6 on 2026-06-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_stock', models.PositiveIntegerField(default=0)),
                ('available_library_stock', models.PositiveIntegerField(default=0)),
                ('store_stock', models.PositiveIntegerField(default=0)),
                ('available_store_stock', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='books.book')),
            ],
        ),
    ]
