# Generated by Django 6.0.6 on 2026-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_inventory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('available_library_stock__gte', 0)), name='library_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('available_store_stock__gte', 0)), name='store_stock_non_negative'),
        ),
    ]
