# Generated by Django 6.0.6 on 2026-08-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        ('inventory', '0003_bookcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='book_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_transactions', to='inventory.bookcopy'),
        ),
    ]
